""" The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1, 3
 6: 1, 2, 3, 6
10: 1, 2, 5, 10
15: 1, 3, 5, 15
21: 1, 3, 7, 21
28: 1, 2, 4, 7, 14, 28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 """  

def getDivisorCount(triangle):
    divisors = 2 # for the purposes of this we can assume we don't care about 1 and that all are divisible by 1 and themselves
    highestPotentialDivisor = int(triangle/2)
    for i in range(2, highestPotentialDivisor):
        if triangle%i == 0:
            divisors += 1
    return(divisors)
    
found = False
currentTriangle = 1
currentNatural = 1

while found == False:
    divisorCount = getDivisorCount(currentTriangle)
    if divisorCount < 501:
        # print(currentTriangle, ' : ', divisorCount)
        currentNatural += 1
        currentTriangle = currentTriangle + currentNatural
    else:
        print(currentTriangle, ' : ', divisorCount)
        found = True


