""" Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. """

fibsUnder4mil = []

def nextFib(a,b):
    c = a + b
    if c < 4000000:
        fibsUnder4mil.append(c)
        nextFib(b, c)

nextFib(0,1)

answer = sum([x for x in fibsUnder4mil if x%2 == 0])

print(answer)

